site_name: Hostess
site_description: documentation for hostess https://github.com/MillionConcepts/hostess
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          filters: []
          show_signature_annotations: false

nav:
  - 'index.md'
  - 'version_history.md'
  - License: 'LICENSE.md'
  - API Reference: 'hostess_api.md'