site_name: Hostess
site_description: documentation for hostess https://github.com/MillionConcepts/pdr
theme:
  name: readthedocs
plugins:
- search
- mkdocstrings

nav:
  - 'index.md'
  - License: 'LICENSE.md'
  - API Reference: 'hostess_api.md'